-- =========================================================================
-- Rexity RPA initial migration
--
-- Generated by hand because the repo was scaffolded without a baseline.
-- After Neon is provisioned (S1-T6) run:
--   npx prisma migrate resolve --applied 20260606120000_init_rpa_schema
-- and then `npx prisma migrate dev` will pick up future schema changes
-- normally.
-- =========================================================================

-- Required for the time-range exclusion constraint that prevents
-- double-booked appointments (S1-T2 / audit CRITICAL-2).
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---- ENUMS ---------------------------------------------------------------

CREATE TYPE "ChannelType" AS ENUM (
  'WEBSITE', 'WHATSAPP', 'VOICE', 'EMAIL', 'SMS', 'INTERNAL'
);

CREATE TYPE "ConversationState" AS ENUM (
  'IDLE', 'DISCLOSURE', 'CONSENT', 'FAQ',
  'BOOKING_COLLECT_DETAILS', 'SLOT_SCANNING', 'SLOT_OFFERED',
  'PENDING_CONFIRMATION', 'CONFIRMED',
  'RESCHEDULE_VERIFY', 'RESCHEDULE_HOLD_NEW_SLOT', 'RESCHEDULE_SWAP',
  'CANCEL_VERIFY', 'CANCELLED',
  'HANDOFF_REQUESTED', 'HANDOFF_ACTIVE',
  'FAILED_SAFE', 'OPTED_OUT'
);

CREATE TYPE "AppointmentStatus" AS ENUM (
  'PENDING', 'CONFIRMED', 'CANCELLED', 'RESCHEDULED', 'EXPIRED'
);

CREATE TYPE "AuditEventType" AS ENUM (
  'STATE_TRANSITION', 'STATE_TRANSITION_REJECTED',
  'WEBHOOK_RECEIVED', 'WEBHOOK_DUPLICATE',
  'IDEMPOTENCY_REPLAY',
  'SESSION_LOCK_ACQUIRED', 'SESSION_LOCK_REJECTED',
  'SAFE_SUMMARY_UPDATED',
  'SUPPRESSION_CREATED',
  'APPOINTMENT_LEASED', 'APPOINTMENT_CONFIRMED',
  'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESCHEDULED',
  'RETENTION_CLEANUP',
  'HANDOFF_REQUESTED',
  'POLICY_BLOCKED'
);

CREATE TYPE "SuppressionReason" AS ENUM (
  'OPT_OUT', 'BOUNCE', 'MANUAL', 'COMPLIANCE'
);

-- ---- LEAD ----------------------------------------------------------------

CREATE TABLE "Lead" (
  "id"          TEXT PRIMARY KEY,
  "name"        TEXT,
  "email"       TEXT,
  "phone"       TEXT,
  "company"     TEXT,
  "service"     TEXT,
  "message"     TEXT,
  "source"      "ChannelType" NOT NULL DEFAULT 'WEBSITE',
  "safeSummary" TEXT,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL
);

CREATE INDEX "Lead_email_idx"     ON "Lead" ("email");
CREATE INDEX "Lead_phone_idx"     ON "Lead" ("phone");
CREATE INDEX "Lead_createdAt_idx" ON "Lead" ("createdAt");

-- ---- APPOINTMENT ---------------------------------------------------------

CREATE TABLE "Appointment" (
  "id"                   TEXT PRIMARY KEY,
  "leadId"               TEXT REFERENCES "Lead"("id") ON DELETE SET NULL,
  "clientName"           TEXT,
  "clientPhone"          TEXT,
  "clientEmail"          TEXT,
  "startTime"            TIMESTAMPTZ NOT NULL,
  "endTime"              TIMESTAMPTZ NOT NULL,
  "status"               "AppointmentStatus" NOT NULL DEFAULT 'PENDING',
  "source"               "ChannelType" NOT NULL,
  "notesSummary"         TEXT,
  "calendarEventId"      TEXT,
  "leaseExpiresAt"       TIMESTAMPTZ,
  "idempotencyKey"       TEXT UNIQUE,
  "rescheduledFromId"    TEXT,
  "verificationSummary"  TEXT,
  "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"            TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Appointment_time_check" CHECK ("startTime" < "endTime")
);

CREATE INDEX "Appointment_clientPhone_idx"    ON "Appointment" ("clientPhone");
CREATE INDEX "Appointment_clientEmail_idx"    ON "Appointment" ("clientEmail");
CREATE INDEX "Appointment_startTime_idx"      ON "Appointment" ("startTime");
CREATE INDEX "Appointment_endTime_idx"        ON "Appointment" ("endTime");
CREATE INDEX "Appointment_status_idx"         ON "Appointment" ("status");
CREATE INDEX "Appointment_leaseExpiresAt_idx" ON "Appointment" ("leaseExpiresAt");

-- ======================================================================
-- AUDIT FIX (CRITICAL-2): exclusion constraint preventing two
-- PENDING/CONFIRMED appointments from overlapping in time.
-- Without this, the application-level overlap check in
-- lib/rpa/calendar.ts has a TOCTOU window and can double-book.
-- ======================================================================
ALTER TABLE "Appointment"
  ADD CONSTRAINT "Appointment_no_overlap_excl"
  EXCLUDE USING gist (
    tstzrange("startTime", "endTime", '[)') WITH &&
  )
  WHERE ("status" IN ('PENDING', 'CONFIRMED'));

-- ---- COMMUNICATION SESSION -----------------------------------------------

CREATE TABLE "CommunicationSession" (
  "id"                    TEXT PRIMARY KEY,
  "leadId"                TEXT REFERENCES "Lead"("id") ON DELETE SET NULL,
  "channelId"             TEXT NOT NULL,
  "channelType"           "ChannelType" NOT NULL,
  "currentState"          "ConversationState" NOT NULL DEFAULT 'IDLE',
  "recordingConsent"      BOOLEAN NOT NULL DEFAULT FALSE,
  "aiDisclosureAccepted"  BOOLEAN NOT NULL DEFAULT FALSE,
  "marketingConsent"      BOOLEAN NOT NULL DEFAULT FALSE,
  "privacyNoticeVersion"  TEXT,
  "consentTimestamp"      TIMESTAMP(3),
  "consentChannel"        TEXT,
  "safeSummary"           TEXT,
  "redactedContext"       JSONB,
  "lockVersion"           INTEGER NOT NULL DEFAULT 0,
  "lockedUntil"           TIMESTAMP(3),
  "lastActive"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"             TIMESTAMP(3) NOT NULL
);

CREATE UNIQUE INDEX "CommunicationSession_channelId_channelType_key"
  ON "CommunicationSession" ("channelId", "channelType");
CREATE INDEX "CommunicationSession_currentState_idx" ON "CommunicationSession" ("currentState");
CREATE INDEX "CommunicationSession_lastActive_idx"   ON "CommunicationSession" ("lastActive");
CREATE INDEX "CommunicationSession_lockedUntil_idx"  ON "CommunicationSession" ("lockedUntil");

-- ---- WEBHOOK EVENT -------------------------------------------------------

CREATE TABLE "WebhookEvent" (
  "id"               TEXT PRIMARY KEY,
  "provider"         TEXT NOT NULL,
  "providerEventId"  TEXT NOT NULL,
  "channelType"      "ChannelType" NOT NULL,
  "idempotencyKey"   TEXT NOT NULL UNIQUE,
  "processedAt"      TIMESTAMP(3),
  "status"           TEXT NOT NULL,
  "errorSummary"     TEXT,
  "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX "WebhookEvent_provider_providerEventId_key"
  ON "WebhookEvent" ("provider", "providerEventId");
CREATE INDEX "WebhookEvent_status_idx"    ON "WebhookEvent" ("status");
CREATE INDEX "WebhookEvent_createdAt_idx" ON "WebhookEvent" ("createdAt");

-- ---- AUDIT EVENT ---------------------------------------------------------

CREATE TABLE "AuditEvent" (
  "id"               TEXT PRIMARY KEY,
  "type"             "AuditEventType" NOT NULL,
  "sessionId"        TEXT,
  "leadId"           TEXT,
  "appointmentId"    TEXT,
  "idempotencyKey"   TEXT,
  "actor"            TEXT NOT NULL,
  "redactedContext"  JSONB,
  "safeSummary"      TEXT,
  "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "AuditEvent_type_idx"          ON "AuditEvent" ("type");
CREATE INDEX "AuditEvent_sessionId_idx"     ON "AuditEvent" ("sessionId");
CREATE INDEX "AuditEvent_appointmentId_idx" ON "AuditEvent" ("appointmentId");
CREATE INDEX "AuditEvent_createdAt_idx"     ON "AuditEvent" ("createdAt");

-- ---- SUPPRESSION ENTRY ---------------------------------------------------

CREATE TABLE "SuppressionEntry" (
  "id"           TEXT PRIMARY KEY,
  "channelType"  "ChannelType" NOT NULL,
  "identifier"   TEXT NOT NULL,
  "reason"       "SuppressionReason" NOT NULL DEFAULT 'OPT_OUT',
  "source"       TEXT,
  "safeSummary"  TEXT,
  "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expiresAt"    TIMESTAMP(3)
);

CREATE UNIQUE INDEX "SuppressionEntry_channelType_identifier_key"
  ON "SuppressionEntry" ("channelType", "identifier");
CREATE INDEX "SuppressionEntry_identifier_idx" ON "SuppressionEntry" ("identifier");
CREATE INDEX "SuppressionEntry_expiresAt_idx"  ON "SuppressionEntry" ("expiresAt");
